version: "3.8"
services:
  api:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:academy@pg-db:5432/postgres?schema=public
      - PORT=8080
      - JWT_SECRET=1q2w3e4r5t6y7u8i9o0p
      - REDIS_URL=redis://cache:6379/
    ports:
      - 8080:8080
    depends_on:
      - pg-db
  pg-db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=academy
    volumes:
      - learnhub-db-vol:/var/lib/postgresql/data
    ports:
      - 5432:5432
  cache:
    image: redis:7.2.3
    expose:
      - 6379
volumes:
  learnhub-db-vol:
    name: 6e61e924c45da62ee4d29cef556004a5bb65f0c0e293bf0c17575234ae0e8e18
