version: "3.8"
services:
  api:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:academy@pg-db:5432/postgres?schema=public
      - PORT=8080
      - JWT_SECRET=1q2w3e4r5t6y7u8i9o0p
      - REDIS_URL=redis://cache:6379/
    ports:
      - 8080:8080
    depends_on:
      pg-db:
        condition: service_healthy
  pg-db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=academy
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 3s
      timeout: 5s
      retries: 5
  cache:
    image: redis:7.2.3
    expose:
      - 6379
volumes:
  db-data:
