name: Docker build image

on: push

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Echo hello-world
        run: echo "Hello, world."
      - name: Where i'm i
        run: pwd
      - name: I don't know
        run: ls
