name: Docker build image

on: push

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print out hello-world
        run: echo "Hello, world."
      - name: Print out current directory
        run: pwd
      - name: Checkout
        uses: actions/checkout@main
      - name:List files and directory
        run: ls
